services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - ./data_db:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
  web:
    build: .
    command: python manage.py runserver
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./restaurant_booking:/home/web